// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title IHonkVerifier
/// @notice Interface for the Noir UltraHonk verifier generated by Barretenberg
interface IHonkVerifier {
    /// @notice Verifies a ZK proof against public inputs
    /// @param proof The proof bytes
    /// @param publicInputs The public inputs to the circuit
    /// @return True if the proof is valid
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external returns (bool);
}
